### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by 3qingmi** [mattymatty97/LTC_LobbyControl#1]
I found that installing LateCompany or Terminal_Tools will render terminal commands invalid. If I type "lobby" in the terminal, the terminal will prompt "Corresponding command not found"

【https://thunderstore.io/c/lethal-company/p/anormaltwig/LateCompany/】
【https://thunderstore.io/c/lethal-company/p/Florent/Terminal_Tools/】

**Comment by Hardeh** [comment]
You don't need LateCompany wheh using this mod

**Comment by mattymatty97** [comment]
this mod is incompatible with LateCompany and will disable itself with an error message if LateCompany is found
