### ISSUE TITLE
[Suggestion] Add ability to lock the ship lever

### ISSUE THREAD

**Issue by gamusgoober** [mattymatty97/LTC_LobbyControl#14]
Add a command that locks the ship lever until the command is used again so people don't unknowingly flip it, unaware someone is trying to join.

Could also 'reuse' the warning you get when you don't land on the company on the last day, so instead of locking it you get a warning saying they may be waiting for something.

**Comment by mattymatty97** [comment]
this should have been implemented in the latest Experimental version as the live one seems to softlock
