### ISSUE TITLE
[Suggestion] Command to change player limit for the lobby if you are using MoreCompany or any lobby size increasing mods

### ISSUE THREAD

**Issue by DeCat4** [mattymatty97/LTC_LobbyControl#16]

**Comment by CoreyHelms** [comment]
Analysis of my own logs indicate that any player past #4 will have connection rejected by this mod. Prior to v60 updates, LobbyControl and MoreCompany seemed to co-exist...not sure if MoreCompany had a code change that broke this, or if something needs to be updated in LobbyControl. 
A configurable setting for player maximum in LobbyControl may alleviate this.

**Comment by DeCat4** [comment]
huh? it worked just fine last time i played, could this do with those item syncing configs? i have those disabled

**Comment by mattymatty97** [comment]
LobbyControl and MoreCompany work perfectly fine together.

sadly while i would be able to reduce the max player number there is no way of increasing it while already inside a lobby
