### ISSUE TITLE
DDoS problem

### ISSUE THREAD

**Issue by Angrymanaboutcomp** [mattymatty97/LTC_LobbyControl#18]
Each time I make a lobby im getting DDoS'd atacked when I use the mod
It's annoying to have to reset my Ip each time and I fear my info getting stolen 
I dont know if it's a vulnerability created by the mod or is it just a vanilla issue but had really bad timing

**Comment by mattymatty97** [comment]
Lobby Control does not have it's own Networking nor goes to a separate Server List. 
all this mod does is keep the Steam Lobby alive so people can join after the first landing.

if you are suffering from frequent DDOS attacks you might have to go the your local authorities.
