### ISSUE TITLE
[Issue] radar fix won't sync to vanilla client (yea so just do fix to skip glitched slot), and after respawn from dead ur hands will disappear (only client-side)

### ISSUE THREAD

**Issue by CoolLKKPS** [mattymatty97/LTC_LobbyControl#3]
same as topic

**Comment by CoolLKKPS** [comment]
@mattymatty97 make sure u check out this host_fixes issue ticket: https://github.com/Charlese2/HostFixes/issues/12
after u checked i will delete the log

**Comment by CoolLKKPS** [comment]
and if activate radar, the player list sequence in the monitor will and still abnormal, only allow 9 players lobby but have "player #7" name in the player 12 slot? (online mode) this should not happen no matter name or slot glitch

**Comment by mattymatty97** [comment]
the names not syncyng/ appearing as Unknown is a vanilla bug, it is on the list of things that i am trying to fix but unless i find what is is causing it as the root it's going to take a while

TL:DR: that is not a bug with the mod but with late Joining in general

**Comment by mattymatty97** [comment]
the linked issue is even less related to this mod :/

**Comment by CoolLKKPS** [comment]
@mattymatty97 will try to get a clearly log for u, bc i did forgot to save the log sry, and i just wake up at this time \@ .. \@

**Comment by CoolLKKPS** [comment]
oops i found this issues that might wasn't cause by this mod, ah sry my bad

**Comment by CoolLKKPS** [comment]
i actually confuse, who fix the monitor bug...

**Comment by CoolLKKPS** [comment]
but anyway if i found the error log that related this mod and really affect the game, will let u know

**Comment by CoolLKKPS** [comment]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameNetcodeStuff.PlayerControllerB.DestroyItemInSlot (System.Int32 itemSlot) (at <af9b1eec498a45aebd42601d6ab85015>:0)
GameNetcodeStuff.PlayerControllerB.DestroyItemInSlotAndSync (System.Int32 itemSlot) (at <af9b1eec498a45aebd42601d6ab85015>:0)
ShotgunItem+<reloadGunAnimation>d__48.MoveNext () (at <af9b1eec498a45aebd42601d6ab85015>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:0)
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameNetcodeStuff.PlayerControllerB.DestroyItemInSlot (System.Int32 itemSlot) (at <af9b1eec498a45aebd42601d6ab85015>:0)
GameNetcodeStuff.PlayerControllerB.DestroyItemInSlotClientRpc (System.Int32 itemSlot) (at <af9b1eec498a45aebd42601d6ab85015>:0)
GameNetcodeStuff.PlayerControllerB.__rpc_handler_899109231 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <af9b1eec498a45aebd42601d6ab85015>:0)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:0)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Logger:LogException(Exception, Object)
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass4_0:<LogException>b__0()
AsyncLoggers.Wrappers.JobWrapper:LogWorker()
AsyncLoggers.Wrappers.LogJob:Execute()
Unity.Jobs.JobStruct`1:Execute(LogJob&, IntPtr, IntPtr, JobRanges&, Int32)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameNetcodeStuff.PlayerControllerB.DestroyItemInSlot (System.Int32 itemSlot) (at <af9b1eec498a45aebd42601d6ab85015>:0)
GameNetcodeStuff.PlayerControllerB.DestroyItemInSlotClientRpc (System.Int32 itemSlot) (at <af9b1eec498a45aebd42601d6ab85015>:0)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::DestroyItemInSlotServerRpc>(GameNetcodeStuff.PlayerControllerB,int)
GameNetcodeStuff.PlayerControllerB.__rpc_handler_1388366573 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <af9b1eec498a45aebd42601d6ab85015>:0)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:0)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Logger:LogException(Exception, Object)
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass4_0:<LogException>b__0()
AsyncLoggers.Wrappers.JobWrapper:LogWorker()
AsyncLoggers.Wrappers.LogJob:Execute()
Unity.Jobs.JobStruct`1:Execute(LogJob&, IntPtr, IntPtr, JobRanges&, Int32)
