### ISSUE TITLE
[Thread] For v2.3.4

### ISSUE THREAD

**Issue by CoolLKKPS** [mattymatty97/LTC_LobbyControl#4]
a simple shotgun reload issue
and idk how does queue work, my friends telling me they spend too many time for waiting the queue, i guess 30s waiting time are way too long

[Error : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameNetcodeStuff.PlayerControllerB.DestroyItemInSlot (System.Int32 itemSlot) (at :0)
GameNetcodeStuff.PlayerControllerB.DestroyItemInSlotAndSync (System.Int32 itemSlot) (at :0)
ShotgunItem+d__48.MoveNext () (at :0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at :0)
[Error : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameNetcodeStuff.PlayerControllerB.DestroyItemInSlot (System.Int32 itemSlot) (at :0)
GameNetcodeStuff.PlayerControllerB.DestroyItemInSlotClientRpc (System.Int32 itemSlot) (at :0)
GameNetcodeStuff.PlayerControllerB.__rpc_handler_899109231 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at :0)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:0)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Logger:LogException(Exception, Object)
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass4_0:b__0()
AsyncLoggers.Wrappers.JobWrapper:LogWorker()
AsyncLoggers.Wrappers.LogJob:Execute()
Unity.Jobs.JobStruct`1:Execute(LogJob&, IntPtr, IntPtr, JobRanges&, Int32)

[Error : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
GameNetcodeStuff.PlayerControllerB.DestroyItemInSlot (System.Int32 itemSlot) (at :0)
GameNetcodeStuff.PlayerControllerB.DestroyItemInSlotClientRpc (System.Int32 itemSlot) (at :0)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::DestroyItemInSlotServerRpc>(GameNetcodeStuff.PlayerControllerB,int)
GameNetcodeStuff.PlayerControllerB.__rpc_handler_1388366573 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at :0)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:0)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Logger:LogException(Exception, Object)
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass4_0:b__0()
AsyncLoggers.Wrappers.JobWrapper:LogWorker()
AsyncLoggers.Wrappers.LogJob:Execute()
Unity.Jobs.JobStruct`1:Execute(LogJob&, IntPtr, IntPtr, JobRanges&, Int32)

**Comment by mattymatty97** [comment]
i don't really see how that could be caused by Lobby Control but with all the other mods throwing exceptions it could be also some broken code form other mods making Lobby Control fail

**Comment by CoolLKKPS** [comment]
so in previous, weather won't update i think bc that cause by malicious mods or just network de-sync, idk
but shotgun issue still happen but not really matter, u can fix that by switching the slot
i still try to collect more error logs in public lobby, wish my luck

But, in current version, everything works fine, gj!

**Comment by mattymatty97** [comment]
thank you for the patience, if you want you can find me in the [Modding discord](https://discord.gg/XeyYqRdRGC)
in the [mod thread](https://discord.com/channels/1168655651455639582/1211989201793449994)
