### ISSUE TITLE
small changelog mistake

### ISSUE THREAD

**Issue by CatsArmy** [mattymatty97/LTC_LobbyControl#5]
## v2.3.0
- added LogSpam fixes (CalculatePolygonPath)
- renamed GhostItems to ItemSync
  - added patch to fix shotguns disappearing if client has de-synced inventory
  - added patch to allow clients to pick up items that already belong to them
- fix scrap not having value/wrong state after hotload
- Yeet dependencies :D

### **SPLIT POINT**
- moved non-host related features to [Matty's Fixes]()

this does not link to the thunderstore of that mod but just the page you are currently on as the () is empty

**Comment by mattymatty97** [comment]
great catch 😂 , will fix in the next update.
