### ISSUE TITLE
bug with late conpany

### ISSUE THREAD

**Issue by azlanders** [mattymatty97/LTC_LobbyControl#6]

**Comment by azlanders** [comment]
in the new ver the mod willbe disabled when late company is enabled

**Comment by azlanders** [comment]
ver 2.2.6 doesnt have this bug

**Comment by mattymatty97** [comment]
LateComapny is inherently incompatible with LobbyControl as they both do the same thing

LobbyControl will automatically disable itself with a popup if an incompatible mod is found!
