### ISSUE TITLE
[Tweak] Auto lobby should be on by default

### ISSUE THREAD

**Issue by epicEaston197** [mattymatty97/LTC_LobbyControl#7]
Auto lobby should be on by default as other similar mods do this by default and it's what users expect they can easily disable this functionality if they use lethal config or manually edit the config through ThunderStore or R2modman

**Comment by mattymatty97** [comment]
auto lobby has been added afterwards because it was requested mutiple times.

the mod started precisely because i did not want the lobby to be open by default but to be able to decide if and when to open it.

**Comment by epicEaston197** [comment]
> auto lobby has been added afterwards because it was requested mutiple times.
> 
> the mod started precisely because i did not want the lobby to be open by default but to be able to decide if and when to open it.

thank you for your response that makes a lot of sense 
I do have one question though if the lobby is open can someone join it while the ship is landed?
That's the whole reason why I turned on auto lobby

**Comment by mattymatty97** [comment]
no, joining while landed is a feature that only LateCompany has and it was never a stable one.. the vanilla game does not support at all that kind of late joining and will 100% cause desync/issues. LateCompany tries to solve the issues by requiring everybody to have the mod installed ( if you use the JoinWhileLanded option ) but is still far from perfect and highly suggested to only allow joininv while in orbit
